'use client'

import { useState } from 'react'
import type { ItineraryItem, Trip } from '@/types'
import { calculateStartTime, formatDate } from '@/lib/utils'

interface Props {
  trip: Trip
  items: ItineraryItem[]
}

export default function ExportPDF({ trip, items }: Props) {
  const [exporting, setExporting] = useState(false)

  async function handleExport() {
    setExporting(true)
    try {
      // Dynamic import to avoid SSR issues
      const jsPDF = (await import('jspdf')).default

      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      const pageWidth = doc.internal.pageSize.getWidth()
      const margin = 20
      let y = 20

      // Title
      doc.setFontSize(20)
      doc.setTextColor(40, 40, 40)
      doc.text('Japan Trip Planner', margin, y)
      y += 10

      // Trip name
      doc.setFontSize(14)
      doc.setTextColor(60, 60, 60)
      doc.text(trip.name, margin, y)
      y += 8

      // Trip info
      doc.setFontSize(10)
      doc.setTextColor(120, 120, 120)
      const infoLine = `${trip.destination}  |  ${trip.days} days  |  ${trip.passengers} passengers  |  Depart: ${trip.depart_date}`
      doc.text(infoLine, margin, y)
      y += 6

      // Divider
      doc.setDrawColor(220, 220, 220)
      doc.line(margin, y, pageWidth - margin, y)
      y += 8

      // Itinerary by day
      for (let day = 1; day <= trip.days; day++) {
        const dayItems = items
          .filter((i) => i.day === day)
          .sort((a, b) => a.order_index - b.order_index)

        if (dayItems.length === 0) continue

        // Check page break
        if (y > 260) {
          doc.addPage()
          y = 20
        }

        // Day header
        doc.setFontSize(12)
        doc.setTextColor(255, 107, 53)
        const dayDate = addDaysToDate(trip.depart_date, day - 1)
        doc.text(`Day ${day}  (${dayDate})`, margin, y)
        y += 7

        // Spots
        doc.setFontSize(9)
        const prevDurations: number[] = []
        dayItems.forEach((item) => {
          if (y > 270) {
            doc.addPage()
            y = 20
          }
          const startTime = calculateStartTime('09:00', prevDurations)
          const endH = addMinutesToTime(startTime, item.duration)
          prevDurations.push(item.duration)

          doc.setTextColor(60, 60, 60)
          doc.text(`${startTime}-${endH}`, margin, y)
          doc.setTextColor(40, 40, 40)
          doc.text(`${item.spot_name}`, margin + 22, y)
          doc.setTextColor(150, 150, 150)
          doc.text(`${item.spot_type} · ${item.duration}min`, margin + 70, y)
          y += 6
        })

        y += 4
      }

      // Budget summary
      if (y > 230) {
        doc.addPage()
        y = 20
      }

      y += 4
      doc.setDrawColor(220, 220, 220)
      doc.line(margin, y, pageWidth - margin, y)
      y += 8

      doc.setFontSize(12)
      doc.setTextColor(255, 107, 53)
      doc.text('Budget Summary', margin, y)
      y += 8

      doc.setFontSize(9)
      doc.setTextColor(60, 60, 60)
      doc.text(`Exchange rate: 1 JPY = 0.22 TWD`, margin, y)
      y += 5

      // Footer
      y = doc.internal.pageSize.getHeight() - 12
      doc.setFontSize(8)
      doc.setTextColor(180, 180, 180)
      doc.text(`Generated by Japan Trip Planner · ${new Date().toLocaleDateString()}`, margin, y)

      doc.save(`${trip.name}-itinerary.pdf`)
    } catch (err) {
      console.error('PDF export error:', err)
      alert('PDF 匯出失敗，請稍後再試')
    } finally {
      setExporting(false)
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="w-full py-3 rounded-xl border border-[rgba(255,255,255,0.12)] text-[#888888] text-sm font-medium hover:border-[rgba(255,255,255,0.25)] hover:text-white transition-all flex items-center justify-center gap-2 disabled:opacity-50"
    >
      {exporting ? (
        <>
          <span className="animate-spin">⏳</span>
          <span>匯出中...</span>
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <span>匯出行程 PDF</span>
        </>
      )}
    </button>
  )
}

function addDaysToDate(dateStr: string, days: number): string {
  const date = new Date(dateStr)
  date.setDate(date.getDate() + days)
  return date.toLocaleDateString('zh-TW', { month: 'numeric', day: 'numeric' })
}

function addMinutesToTime(time: string, minutes: number): string {
  const [h, m] = time.split(':').map(Number)
  const total = h * 60 + m + minutes
  const newH = Math.floor(total / 60) % 24
  const newM = total % 60
  return `${String(newH).padStart(2, '0')}:${String(newM).padStart(2, '0')}`
}
