import type { Spot } from '@/types'

export const SPOTS: Spot[] = [
  // 東京
  {
    id: 'tokyo-senso-ji',
    name: '淺草寺',
    nameEn: 'Senso-ji Temple',
    destination: '東京',
    type: '神社',
    emoji: '⛩️',
    duration: 90,
    openTime: '06:00-17:00',
    tip: '建議早上參觀避開人潮，雷門拍照最佳時間是清晨',
    lat: 35.7148,
    lng: 139.7967,
  },
  {
    id: 'tokyo-shinjuku-gyoen',
    name: '新宿御苑',
    nameEn: 'Shinjuku Gyoen',
    destination: '東京',
    type: '自然',
    emoji: '🌸',
    duration: 120,
    openTime: '09:00-16:30',
    tip: '春天賞櫻最佳地點，需購票入場約500日圓',
    lat: 35.6852,
    lng: 139.7100,
  },
  {
    id: 'tokyo-shibuya-crossing',
    name: '澀谷十字路口',
    nameEn: 'Shibuya Crossing',
    destination: '東京',
    type: '文化',
    emoji: '🚦',
    duration: 60,
    openTime: '全天',
    tip: '二樓星巴克可俯瞰全景，晚上霓虹燈最壯觀',
    lat: 35.6595,
    lng: 139.7004,
  },
  {
    id: 'tokyo-tsukiji',
    name: '築地市場',
    nameEn: 'Tsukiji Market',
    destination: '東京',
    type: '美食',
    emoji: '🐟',
    duration: 90,
    openTime: '05:00-14:00',
    tip: '早上5-6點可看鮪魚拍賣，必吃海鮮丼飯',
    lat: 35.6654,
    lng: 139.7707,
  },
  {
    id: 'tokyo-odaiba',
    name: '台場',
    nameEn: 'Odaiba',
    destination: '東京',
    type: '購物',
    emoji: '🗼',
    duration: 180,
    openTime: '11:00-21:00',
    tip: '可搭乘百合鷗號欣賞彩虹大橋，DiverCity有鋼彈立像',
    lat: 35.6267,
    lng: 139.7750,
  },
  {
    id: 'tokyo-ueno',
    name: '上野公園',
    nameEn: 'Ueno Park',
    destination: '東京',
    type: '文化',
    emoji: '🏛️',
    duration: 120,
    openTime: '05:00-23:00',
    tip: '附近有多個博物館，上野動物園可以看熊貓',
    lat: 35.7146,
    lng: 139.7741,
  },
  {
    id: 'tokyo-akihabara',
    name: '秋葉原',
    nameEn: 'Akihabara',
    destination: '東京',
    type: '購物',
    emoji: '🎮',
    duration: 150,
    openTime: '10:00-21:00',
    tip: '電器、動漫、周邊應有盡有，記得比價後再買',
    lat: 35.7022,
    lng: 139.7741,
  },

  // 大阪
  {
    id: 'osaka-dotonbori',
    name: '道頓堀',
    nameEn: 'Dotonbori',
    destination: '大阪',
    type: '美食',
    emoji: '🦞',
    duration: 120,
    openTime: '全天',
    tip: '必吃章魚燒、大阪燒，格力高男跑步廣告板必拍',
    lat: 34.6687,
    lng: 135.5013,
  },
  {
    id: 'osaka-castle',
    name: '大阪城',
    nameEn: 'Osaka Castle',
    destination: '大阪',
    type: '文化',
    emoji: '🏯',
    duration: 120,
    openTime: '09:00-17:00',
    tip: '天守閣內有豐臣秀吉相關展覽，春天賞櫻絕美',
    lat: 34.6873,
    lng: 135.5259,
  },
  {
    id: 'osaka-shinsaibashi',
    name: '心齋橋',
    nameEn: 'Shinsaibashi',
    destination: '大阪',
    type: '購物',
    emoji: '🛍️',
    duration: 150,
    openTime: '11:00-21:00',
    tip: '大阪最繁華購物街，藥妝店密集，可用退稅',
    lat: 34.6726,
    lng: 135.5011,
  },
  {
    id: 'osaka-kuromon',
    name: '黑門市場',
    nameEn: 'Kuromon Market',
    destination: '大阪',
    type: '美食',
    emoji: '🐡',
    duration: 90,
    openTime: '08:00-18:00',
    tip: '大阪廚房，新鮮海鮮現買現吃，邊走邊吃最過癮',
    lat: 34.6684,
    lng: 135.5090,
  },
  {
    id: 'osaka-tsutenkaku',
    name: '通天閣',
    nameEn: 'Tsutenkaku Tower',
    destination: '大阪',
    type: '文化',
    emoji: '🗼',
    duration: 60,
    openTime: '10:00-20:00',
    tip: '新世界地標，周邊串炸名店林立，摸比利肯像帶來好運',
    lat: 34.6524,
    lng: 135.5063,
  },
  {
    id: 'osaka-kaiyukan',
    name: '海遊館',
    nameEn: 'Osaka Aquarium Kaiyukan',
    destination: '大阪',
    type: '自然',
    emoji: '🐋',
    duration: 150,
    openTime: '10:00-20:00',
    tip: '世界最大水族館之一，鯨鯊水槽震撼人心',
    lat: 34.6546,
    lng: 135.4282,
  },

  // 京都
  {
    id: 'kyoto-kinkakuji',
    name: '金閣寺',
    nameEn: 'Kinkakuji Temple',
    destination: '京都',
    type: '神社',
    emoji: '✨',
    duration: 90,
    openTime: '09:00-17:00',
    tip: '早上9點開門人少，金色倒影在晴天最漂亮',
    lat: 35.0394,
    lng: 135.7292,
  },
  {
    id: 'kyoto-arashiyama',
    name: '嵐山竹林',
    nameEn: 'Arashiyama Bamboo Grove',
    destination: '京都',
    type: '自然',
    emoji: '🎋',
    duration: 90,
    openTime: '全天',
    tip: '清晨人少最佳，可搭嵐電前往，附近有渡月橋',
    lat: 35.0162,
    lng: 135.6716,
  },
  {
    id: 'kyoto-fushimi',
    name: '伏見稻荷',
    nameEn: 'Fushimi Inari Shrine',
    destination: '京都',
    type: '神社',
    emoji: '⛩️',
    duration: 150,
    openTime: '全天',
    tip: '千本鳥居壯觀，山頂需步行約2小時，建議穿輕便鞋',
    lat: 34.9671,
    lng: 135.7727,
  },
  {
    id: 'kyoto-kiyomizudera',
    name: '清水寺',
    nameEn: 'Kiyomizudera Temple',
    destination: '京都',
    type: '神社',
    emoji: '🏯',
    duration: 120,
    openTime: '06:00-18:00',
    tip: '清水舞台懸空而建，二三年坂石板路有眾多抹茶甜點店',
    lat: 34.9949,
    lng: 135.7851,
  },
  {
    id: 'kyoto-nishiki',
    name: '錦市場',
    nameEn: 'Nishiki Market',
    destination: '京都',
    type: '美食',
    emoji: '🍡',
    duration: 90,
    openTime: '09:00-18:00',
    tip: '京都廚房，有各式醃漬物、豆腐、京漬物等道地食材',
    lat: 35.0050,
    lng: 135.7657,
  },
  {
    id: 'kyoto-nijo',
    name: '二条城',
    nameEn: 'Nijo Castle',
    destination: '京都',
    type: '文化',
    emoji: '🏯',
    duration: 120,
    openTime: '08:45-17:00',
    tip: '聲音廊道走過會發出鶯啼聲，是德川幕府重要遺址',
    lat: 35.0142,
    lng: 135.7481,
  },

  // 京都 補充2
  {
    id: 'kyoto-tofukuji',
    name: '東福寺',
    nameEn: 'Tofukuji Temple',
    destination: '京都',
    type: '神社',
    emoji: '🍁',
    duration: 90,
    openTime: '09:00-16:30',
    tip: '京都賞楓最熱門寺院，通天橋紅葉隧道是秋天必訪，避開11月週末人潮',
    lat: 34.9745,
    lng: 135.7718,
  },
  {
    id: 'kyoto-ryoanji',
    name: '龍安寺',
    nameEn: 'Ryoanji Temple',
    destination: '京都',
    type: '神社',
    emoji: '🪨',
    duration: 60,
    openTime: '08:00-17:00',
    tip: '世界最著名枯山水庭園，15塊石頭的謎題讓人靜思，附近可串金閣寺',
    lat: 35.0344,
    lng: 135.7184,
  },
  {
    id: 'kyoto-ginkakuji',
    name: '銀閣寺',
    nameEn: 'Ginkakuji Temple',
    destination: '京都',
    type: '神社',
    emoji: '✨',
    duration: 60,
    openTime: '08:30-17:00',
    tip: '與哲學之道相連，苔庭和砂盆獨具禪意，比金閣寺更幽靜',
    lat: 35.0268,
    lng: 135.7982,
  },
  {
    id: 'kyoto-yasaka',
    name: '八坂神社',
    nameEn: 'Yasaka Shrine',
    destination: '京都',
    type: '神社',
    emoji: '⛩️',
    duration: 45,
    openTime: '全天',
    tip: '祇園中心地標，祇園祭的主辦神社，夜晚點燈後氣氛絕佳',
    lat: 35.0037,
    lng: 135.7785,
  },
  {
    id: 'kyoto-heian',
    name: '平安神宮',
    nameEn: 'Heian Shrine',
    destination: '京都',
    type: '神社',
    emoji: '⛩️',
    duration: 60,
    openTime: '06:00-18:00',
    tip: '朱紅色巨大鳥居是京都地標之一，神苑春天枝垂櫻花絕美',
    lat: 35.0164,
    lng: 135.7824,
  },

  // 福岡
  {
    id: 'fukuoka-dazaifu',
    name: '太宰府天滿宮',
    nameEn: 'Dazaifu Tenmangu',
    destination: '福岡',
    type: '神社',
    emoji: '⛩️',
    duration: 120,
    openTime: '06:30-19:00',
    tip: '學問之神菅原道真供奉處，必吃參道梅枝餅',
    lat: 33.5124,
    lng: 130.5340,
  },
  {
    id: 'fukuoka-nakasu',
    name: '中洲屋台',
    nameEn: 'Nakasu Yatai',
    destination: '福岡',
    type: '美食',
    emoji: '🍜',
    duration: 120,
    openTime: '18:00-01:00',
    tip: '露天屋台文化是福岡特色，必吃博多拉麵、明太子',
    lat: 33.5904,
    lng: 130.4017,
  },
  {
    id: 'fukuoka-canal-city',
    name: '博多運河城',
    nameEn: 'Canal City Hakata',
    destination: '福岡',
    type: '購物',
    emoji: '🛍️',
    duration: 150,
    openTime: '10:00-21:00',
    tip: '複合式購物中心，有真實運河穿過，整點有噴水表演',
    lat: 33.5902,
    lng: 130.4112,
  },
  {
    id: 'fukuoka-castle',
    name: '福岡城跡',
    nameEn: 'Fukuoka Castle Ruins',
    destination: '福岡',
    type: '文化',
    emoji: '🏯',
    duration: 90,
    openTime: '全天',
    tip: '舞鶴公園內，春天賞櫻名所，可遠眺福岡市景',
    lat: 33.5864,
    lng: 130.3844,
  },

  // 福岡 補充
  {
    id: 'fukuoka-tenjin',
    name: '天神',
    nameEn: 'Tenjin',
    destination: '福岡',
    type: '購物',
    emoji: '🏬',
    duration: 150,
    openTime: '10:00-21:00',
    tip: '福岡最大購物區，天神地下街連結多棟百貨，藥妝和服飾應有盡有',
    lat: 33.5903,
    lng: 130.3976,
  },
  {
    id: 'fukuoka-mojiko',
    name: '門司港',
    nameEn: 'Mojiko',
    destination: '福岡',
    type: '文化',
    emoji: '🚢',
    duration: 180,
    openTime: '全天',
    tip: '明治大正時代紅磚建築群，烤咖哩是當地名物，香蕉人是吉祥物',
    lat: 33.9447,
    lng: 130.9638,
  },
  {
    id: 'fukuoka-yanagawa',
    name: '柳川',
    nameEn: 'Yanagawa',
    destination: '福岡',
    type: '自然',
    emoji: '🚣',
    duration: 180,
    openTime: '09:00-17:00',
    tip: '搭遊船穿梭水鄉城下町，鰻魚飯是柳川名物，春天雛祭最熱鬧',
    lat: 33.1629,
    lng: 130.4079,
  },

  // 沖繩
  {
    id: 'okinawa-shuri',
    name: '首里城',
    nameEn: 'Shuri Castle',
    destination: '沖繩',
    type: '文化',
    emoji: '🏯',
    duration: 120,
    openTime: '08:30-18:00',
    tip: '琉球王國象徵，2019年火災後重建中，仍值得一訪',
    lat: 26.2172,
    lng: 127.7194,
  },
  {
    id: 'okinawa-churaumi',
    name: '美ら海水族館',
    nameEn: 'Churaumi Aquarium',
    destination: '沖繩',
    type: '自然',
    emoji: '🐠',
    duration: 180,
    openTime: '08:30-18:30',
    tip: '世界第二大水族館，鯨鯊與魟魚共游的大水槽令人震撼',
    lat: 26.6941,
    lng: 127.8781,
  },
  {
    id: 'okinawa-kokusai',
    name: '國際通り',
    nameEn: 'Kokusai Street',
    destination: '沖繩',
    type: '購物',
    emoji: '🛍️',
    duration: 120,
    openTime: '10:00-22:00',
    tip: '那霸最熱鬧購物街，泡盛、紅型染、琉球玻璃等特產',
    lat: 26.2166,
    lng: 127.6894,
  },
  {
    id: 'okinawa-kouri',
    name: '古宇利島',
    nameEn: 'Kouri Island',
    destination: '沖繩',
    type: '自然',
    emoji: '🏝️',
    duration: 150,
    openTime: '全天',
    tip: '古宇利大橋開車前往，心形岩石是打卡名所，海水清澈',
    lat: 26.8412,
    lng: 128.0259,
  },

  // 東京 補充
  {
    id: 'tokyo-station',
    name: '東京車站',
    nameEn: 'Tokyo Station',
    destination: '東京',
    type: '交通',
    emoji: '🚉',
    duration: 60,
    openTime: '全天',
    tip: '丸之內紅磚站體是打卡名所，地下街有各式伴手禮',
    lat: 35.6812,
    lng: 139.7671,
  },
  {
    id: 'tokyo-skytree',
    name: '東京晴空塔',
    nameEn: 'Tokyo Skytree',
    destination: '東京',
    type: '景點',
    emoji: '🗼',
    duration: 120,
    openTime: '10:00-21:00',
    tip: '世界第二高塔，天望甲板可俯瞰東京全景，建議提前購票',
    lat: 35.7101,
    lng: 139.8107,
  },
  {
    id: 'tokyo-ginza',
    name: '銀座',
    nameEn: 'Ginza',
    destination: '東京',
    type: '購物',
    emoji: '🛍️',
    duration: 150,
    openTime: '11:00-21:00',
    tip: '東京最高級購物街，假日中央通封街成行人徒步區',
    lat: 35.6717,
    lng: 139.7650,
  },
  {
    id: 'tokyo-harajuku',
    name: '原宿竹下通',
    nameEn: 'Takeshita Street Harajuku',
    destination: '東京',
    type: '購物',
    emoji: '🎀',
    duration: 90,
    openTime: '10:00-20:00',
    tip: '年輕流行文化發源地，可麗餅和棉花糖必吃',
    lat: 35.6702,
    lng: 139.7027,
  },
  {
    id: 'tokyo-meiji',
    name: '明治神宮',
    nameEn: 'Meiji Shrine',
    destination: '東京',
    type: '神社',
    emoji: '⛩️',
    duration: 90,
    openTime: '日出-日落',
    tip: '都心中的森林，初詣時日本最多人參拜的神社',
    lat: 35.6763,
    lng: 139.6993,
  },
  {
    id: 'tokyo-tower',
    name: '東京鐵塔',
    nameEn: 'Tokyo Tower',
    destination: '東京',
    type: '景點',
    emoji: '🗼',
    duration: 90,
    openTime: '09:00-23:00',
    tip: '333公尺高的地標，夜晚點燈最美，附近增上寺可同框拍照',
    lat: 35.6586,
    lng: 139.7454,
  },
  {
    id: 'tokyo-ikebukuro',
    name: '池袋',
    nameEn: 'Ikebukuro',
    destination: '東京',
    type: '購物',
    emoji: '🏬',
    duration: 150,
    openTime: '10:00-21:00',
    tip: '動漫聖地之一，乙女路和太陽城是重點，餐廳選擇豐富',
    lat: 35.7295,
    lng: 139.7109,
  },
  {
    id: 'tokyo-roppongi',
    name: '六本木',
    nameEn: 'Roppongi',
    destination: '東京',
    type: '文化',
    emoji: '🎨',
    duration: 120,
    openTime: '11:00-22:00',
    tip: '六本木Hills和森美術館是藝術愛好者必訪，夜生活也很豐富',
    lat: 35.6627,
    lng: 139.7313,
  },
  {
    id: 'tokyo-nakameguro',
    name: '中目黑',
    nameEn: 'Nakameguro',
    destination: '東京',
    type: '文化',
    emoji: '🌸',
    duration: 120,
    openTime: '全天',
    tip: '目黑川沿岸春天櫻花隧道絕美，個性咖啡廳和選品店林立',
    lat: 35.6438,
    lng: 139.6994,
  },
  {
    id: 'tokyo-shinjuku',
    name: '新宿',
    nameEn: 'Shinjuku',
    destination: '東京',
    type: '購物',
    emoji: '🌆',
    duration: 180,
    openTime: '全天',
    tip: '世界最繁忙車站，東口電器街、西口摩天樓、歌舞伎町夜生活各有特色',
    lat: 35.6938,
    lng: 139.7034,
  },

  // 東京 補充2
  {
    id: 'tokyo-omotesando',
    name: '表參道',
    nameEn: 'Omotesando',
    destination: '東京',
    type: '購物',
    emoji: '🌿',
    duration: 120,
    openTime: '11:00-21:00',
    tip: '東京最時尚的林蔭大道，各大精品旗艦店與個性咖啡廳林立',
    lat: 35.6652,
    lng: 139.7133,
  },
  {
    id: 'tokyo-daikanyama',
    name: '代官山',
    nameEn: 'Daikanyama',
    destination: '東京',
    type: '文化',
    emoji: '☕',
    duration: 90,
    openTime: '全天',
    tip: '低調奢華的街區，蔦屋書店是必訪地標，咖啡廳和選品店密集',
    lat: 35.6484,
    lng: 139.7032,
  },
  {
    id: 'tokyo-shimokitazawa',
    name: '下北澤',
    nameEn: 'Shimokitazawa',
    destination: '東京',
    type: '文化',
    emoji: '🎸',
    duration: 120,
    openTime: '全天',
    tip: '東京次文化發源地，古著店、小劇場、Live House聚集的文青聖地',
    lat: 35.6613,
    lng: 139.6681,
  },
  {
    id: 'tokyo-asakusa',
    name: '淺草',
    nameEn: 'Asakusa',
    destination: '東京',
    type: '文化',
    emoji: '🏮',
    duration: 120,
    openTime: '全天',
    tip: '東京最具江戶風情的老街，仲見世通商店街伴手禮選擇豐富',
    lat: 35.7147,
    lng: 139.7966,
  },
  {
    id: 'tokyo-toyosu',
    name: '豐洲市場',
    nameEn: 'Toyosu Market',
    destination: '東京',
    type: '美食',
    emoji: '🐟',
    duration: 120,
    openTime: '05:00-15:00',
    tip: '築地市場的繼承者，頂級鮪魚競標觀光需事先預約',
    lat: 35.6455,
    lng: 139.7853,
  },
  {
    id: 'tokyo-disneyland',
    name: '東京迪士尼樂園',
    nameEn: 'Tokyo Disneyland',
    destination: '東京',
    type: '景點',
    emoji: '🏰',
    duration: 480,
    openTime: '08:00-22:00',
    tip: '提前網路購票，熱門設施用DPA快速通關，煙火秀不可錯過',
    lat: 35.6329,
    lng: 139.8804,
  },
  {
    id: 'tokyo-disneysea',
    name: '東京迪士尼海洋',
    nameEn: 'Tokyo DisneySea',
    destination: '東京',
    type: '景點',
    emoji: '🌊',
    duration: 480,
    openTime: '08:00-22:00',
    tip: '全球唯一，地中海港灣和神秘島是最受歡迎的主題區',
    lat: 35.6267,
    lng: 139.8850,
  },
  {
    id: 'tokyo-ueno-zoo',
    name: '上野動物園',
    nameEn: 'Ueno Zoo',
    destination: '東京',
    type: '自然',
    emoji: '🐼',
    duration: 150,
    openTime: '09:30-17:00',
    tip: '日本最古老動物園，大熊貓是明星動物，春天賞櫻人潮洶湧',
    lat: 35.7163,
    lng: 139.7719,
  },
  {
    id: 'tokyo-yanaka',
    name: '谷中銀座',
    nameEn: 'Yanaka Ginza',
    destination: '東京',
    type: '文化',
    emoji: '🏘️',
    duration: 90,
    openTime: '10:00-18:00',
    tip: '保留昭和風情的老街，下午茶配貓咪是谷中散步的標準行程',
    lat: 35.7273,
    lng: 139.7696,
  },

  // 大阪 補充
  {
    id: 'osaka-station',
    name: '大阪車站',
    nameEn: 'Osaka Station',
    destination: '大阪',
    type: '交通',
    emoji: '🚉',
    duration: 30,
    openTime: '全天',
    tip: '梅田地區核心，周邊百貨連成地下街迷宮',
    lat: 35.7024,
    lng: 135.4959,
  },
  {
    id: 'osaka-umeda',
    name: '梅田',
    nameEn: 'Umeda',
    destination: '大阪',
    type: '購物',
    emoji: '🏬',
    duration: 150,
    openTime: '10:00-21:00',
    tip: '大阪最大購物區，HEP FIVE摩天輪是地標，地下街規模龐大',
    lat: 34.7017,
    lng: 135.4959,
  },
  {
    id: 'osaka-usj',
    name: 'USJ',
    nameEn: 'Universal Studios Japan',
    destination: '大阪',
    type: '景點',
    emoji: '🎢',
    duration: 480,
    openTime: '09:00-21:00',
    tip: '哈利波特魔法世界和任天堂世界是熱門區域，建議購買快速通關',
    lat: 34.6654,
    lng: 135.4323,
  },
  {
    id: 'osaka-namba',
    name: '難波',
    nameEn: 'Namba',
    destination: '大阪',
    type: '購物',
    emoji: '🎭',
    duration: 180,
    openTime: '全天',
    tip: '道頓堀旁，心齋橋筋商店街、黑門市場、難波Parks都在附近',
    lat: 34.6687,
    lng: 135.5014,
  },

  // 大阪 補充2
  {
    id: 'osaka-tennoji',
    name: '天王寺',
    nameEn: 'Tennoji',
    destination: '大阪',
    type: '文化',
    emoji: '🌆',
    duration: 120,
    openTime: '全天',
    tip: '阿倍野HARUKAS是日本最高大廈，天王寺動物園和四天王寺都在附近',
    lat: 34.6467,
    lng: 135.5136,
  },
  {
    id: 'osaka-shinsekai',
    name: '新世界',
    nameEn: 'Shinsekai',
    destination: '大阪',
    type: '文化',
    emoji: '🍢',
    duration: 90,
    openTime: '全天',
    tip: '昭和復古風情街區，串炸發源地，通天閣就在旁邊',
    lat: 34.6519,
    lng: 135.5063,
  },
  {
    id: 'osaka-expo',
    name: '萬博紀念公園',
    nameEn: 'Expo Commemoration Park',
    destination: '大阪',
    type: '自然',
    emoji: '🌳',
    duration: 150,
    openTime: '09:30-17:00',
    tip: '太陽之塔是岡本太郎的代表作，春天日本庭園賞梅賞櫻超美',
    lat: 34.8054,
    lng: 135.5265,
  },

  // 京都 補充
  {
    id: 'kyoto-gion',
    name: '祇園',
    nameEn: 'Gion',
    destination: '京都',
    type: '文化',
    emoji: '🏮',
    duration: 120,
    openTime: '全天',
    tip: '花見小路可能遇到舞妓，白川附近石板路最有氣氛',
    lat: 35.0038,
    lng: 135.7758,
  },
  {
    id: 'kyoto-philosopher',
    name: '哲學之道',
    nameEn: "Philosopher's Path",
    destination: '京都',
    type: '自然',
    emoji: '🌸',
    duration: 90,
    openTime: '全天',
    tip: '沿琵琶湖疏水道兩岸種滿櫻花，春天是京都最美的散步道',
    lat: 35.0270,
    lng: 135.7937,
  },

  // 沖繩 補充
  {
    id: 'okinawa-american-village',
    name: '美國村',
    nameEn: 'American Village',
    destination: '沖繩',
    type: '購物',
    emoji: '🎡',
    duration: 150,
    openTime: '10:00-24:00',
    tip: '美軍基地旁發展的美式購物娛樂區，夕陽西下海景絕美，夜晚摩天輪亮燈',
    lat: 26.3164,
    lng: 127.7575,
  },
  {
    id: 'okinawa-senagajima',
    name: '瀬長島',
    nameEn: 'Senagajima Island',
    destination: '沖繩',
    type: '自然',
    emoji: '✈️',
    duration: 90,
    openTime: '全天',
    tip: '可近距離欣賞飛機起降，Umikaji Terrace地中海風格商店群是打卡熱點',
    lat: 26.1942,
    lng: 127.6467,
  },
  {
    id: 'okinawa-gyokusendo',
    name: '玉泉洞',
    nameEn: 'Gyokusendo Cave',
    destination: '沖繩',
    type: '自然',
    emoji: '🦇',
    duration: 120,
    openTime: '09:00-18:00',
    tip: '日本最長鐘乳石洞，全長5公里，洞內有30萬根鐘乳石',
    lat: 26.1296,
    lng: 127.7700,
  },

  // 札幌
  {
    id: 'sapporo-odori',
    name: '大通公園',
    nameEn: 'Odori Park',
    destination: '札幌',
    type: '自然',
    emoji: '🌳',
    duration: 90,
    openTime: '全天',
    tip: '貫穿市中心，冬季雪祭會場，夏季啤酒花園超熱鬧',
    lat: 43.0601,
    lng: 141.3529,
  },
  {
    id: 'sapporo-beer-museum',
    name: '札幌啤酒博物館',
    nameEn: 'Sapporo Beer Museum',
    destination: '札幌',
    type: '文化',
    emoji: '🍺',
    duration: 90,
    openTime: '11:00-18:00',
    tip: '明治時代紅磚建築，可試飲三種生啤酒，附近有成吉思汗烤肉',
    lat: 43.0714,
    lng: 141.3559,
  },
  {
    id: 'sapporo-tanuki',
    name: '狸小路',
    nameEn: 'Tanukikoji Shopping Street',
    destination: '札幌',
    type: '購物',
    emoji: '🛍️',
    duration: 120,
    openTime: '10:00-21:00',
    tip: '有屋頂的商店街全長約1公里，藥妝店、拉麵店聚集',
    lat: 43.0560,
    lng: 141.3513,
  },
  {
    id: 'sapporo-maruyama',
    name: '円山公園',
    nameEn: 'Maruyama Park',
    destination: '札幌',
    type: '自然',
    emoji: '🌸',
    duration: 90,
    openTime: '全天',
    tip: '附近有北海道神宮，春天賞櫻美麗，秋天紅葉也很推薦',
    lat: 43.0560,
    lng: 141.3208,
  },

  // 札幌 補充
  {
    id: 'sapporo-otaru',
    name: '小樽',
    nameEn: 'Otaru',
    destination: '札幌',
    type: '文化',
    emoji: '🕯️',
    duration: 180,
    openTime: '全天',
    tip: '運河倉庫群是北海道最浪漫景點，玻璃工藝品和壽司是必買必吃',
    lat: 43.1907,
    lng: 140.9947,
  },
  {
    id: 'sapporo-shiroi-koibito',
    name: '白色戀人公園',
    nameEn: 'Shiroi Koibito Park',
    destination: '札幌',
    type: '文化',
    emoji: '🍪',
    duration: 90,
    openTime: '10:00-18:00',
    tip: '北海道最著名伴手禮白色戀人的主題工廠，可DIY製作巧克力',
    lat: 43.0838,
    lng: 141.3196,
  },
  {
    id: 'sapporo-moiwa',
    name: '藻岩山',
    nameEn: 'Mt. Moiwa',
    destination: '札幌',
    type: '自然',
    emoji: '🌃',
    duration: 120,
    openTime: '13:00-22:00',
    tip: '日本新三大夜景之一，纜車上山，札幌市區夜景一覽無遺',
    lat: 43.0267,
    lng: 141.3196,
  },
  {
    id: 'sapporo-hokudai',
    name: '北海道大學',
    nameEn: 'Hokkaido University',
    destination: '札幌',
    type: '自然',
    emoji: '🌲',
    duration: 90,
    openTime: '全天',
    tip: '銀杏大道秋天金黃壯觀，克拉克博士雕像是必拍，免費入場',
    lat: 43.0770,
    lng: 141.3407,
  },
]

export function getSpotsByDestination(destination: string): Spot[] {
  return SPOTS.filter((spot) => spot.destination === destination)
}

export function getSpotById(id: string): Spot | undefined {
  return SPOTS.find((spot) => spot.id === id)
}

export function getSpotByName(name: string): Spot | undefined {
  return SPOTS.find((spot) => spot.name === name || spot.nameEn === name)
}

export function getSpotTypes(destination: string): string[] {
  const spots = getSpotsByDestination(destination)
  return [...new Set(spots.map((s) => s.type))]
}
